# Generated by Django 4.1.13 on 2024-04-24 02:41

from django.db import migrations, models
import tasks.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='First name')),
                ('description', models.CharField(max_length=255, verbose_name='Last name')),
                ('reminderDate', models.DateTimeField(verbose_name='Reminder Date')),
                ('priority', models.IntegerField(choices=[(1, 'HIGH'), (2, 'MEDIUM'), (3, 'LOW')], default=tasks.utils.PriorityTypes['LOW'])),
                ('frequency', models.CharField(max_length=255, verbose_name='Frequency')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
    ]
